[project]
name = "mineru-app"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "dataclasses-json>=0.6.7",
    "gradio>=5.34.2",
    "gradio-pdf>=0.0.22",
    "mineru>=2.0.6",
]

[tool.uv]
package = false
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
